"""Top-level package for InkGen."""

from .baird import (
    BAIRD_INCH_MICRONS,
    BairdDegradationResult,
    BairdParams,
    baird_degrade,
    baird_degrade_asset,
    sigma_px_to_um,
    sigma_um_to_px,
)
from .boundary import Boundary, Canvas
from .cad_component_groups import Zoning
from .component import Component, ComponentGroup, StandardDrawingComponent, TextComponent
from .document import Document, Layer, Layers
from .document_outputs import DocumentOutputFormat, FlowDocument
from .drawing_components import (
    ArcDrawing,
    CircleDrawing,
    CubicBezierDrawing,
    DrawingComponentGroup,
    ImageDrawing,
    LineDrawing,
    OutputFormat,
    PathDrawing,
    PolygonalDrawing,
    QuadraticBezierDrawing,
    RectangleDrawing,
    RegularPolygonDrawing,
    TextDrawing,
    ZoningDrawing,
)
from .dxf_generator import DXFDocument, DXFRenderContext
from .errors import (
    ComponentGroupCollision,
    ComponentGroupOffCanvas,
    IllegalArgumentError,
    IncompatibleCanvas,
    InvalidComponentGroupID,
    InvalidComponentID,
    InvalidConvexHull,
    InvalidPolygonError,
)
from .extraction_truth import (
    ExtractionTruthAnnotation,
    ExtractionTruthRecord,
    annotate_extraction_truth,
    extraction_truth_json,
)
from .gradients import GradientStop, LinearGradientFill
from .grammar_truth import (
    GrammarTruthAnnotation,
    GrammarTruthRecord,
    annotate_grammar_truth,
    grammar_truth_json,
)
from .image_assets import RasterImageAsset, RasterImageComponent
from .paragraph import LineSpacingRule, Paragraph, ParagraphAlignment, ParagraphLine, TabStop
from .parser_stress_fixtures import (
    DEFAULT_PARSER_STRESS_BOM_ROWS,
    ParserStressBOMRow,
    ParserStressFixtureSpec,
    ScannedParserStressFixtureSpec,
    build_parser_stress_pdf,
    build_scanned_parser_stress_pdf,
)
from .pdf_generator import (
    ArcPDF,
    CirclePDF,
    ComponentGroupPDF,
    CubicBezierPDF,
    DocumentPDF,
    ImagePDF,
    LinePDF,
    PathPDF,
    PDFGeneratorInterface,
    PDFRenderContext,
    PolygonalPDF,
    QuadraticBezierPDF,
    RectanglePDF,
    RegularPolygonPDF,
    TextPDF,
)
from .raster_renderer import RasterBairdResult, RasterRenderResult, render_and_degrade_drawing_group, render_drawing_group
from .region_svg import PositionedTextRun, SvgClipWindow, emit_svg_region
from .style import DrawingStyle, Font, Style, TextStyle
from .svg_generator import (
    ArcSVG,
    CircleSVG,
    ComponentGroupSVG,
    CubicBezierSVG,
    DocumentSVG,
    ImageSVG,
    IncludeLayer,
    LineSVG,
    PathSVG,
    PolygonalSVG,
    QuadraticBezierSVG,
    RectangleSVG,
    RegularPolygonSVG,
    SVGComponent,
    TableSVG,
    TextSVG,
)
from .svg_utils import FlattenedPath, FlattenedSVG, flatten_svg
from .table import AutoFitRule, Cell, Column, Row, Table
from .text_fitter import (
    FitterShape,
    FittingResult,
    TextBlock,
    TextFitter,
    component_to_fitter_shape,
)
from .text_outline import outline_for_text, outline_for_text_bytes

__version__ = "0.1.0"

__all__ = [
    "ArcSVG",
    "ArcDrawing",
    "ArcPDF",
    "AutoFitRule",
    "BAIRD_INCH_MICRONS",
    "BairdDegradationResult",
    "BairdParams",
    "Boundary",
    "Canvas",
    "Cell",
    "CircleSVG",
    "CircleDrawing",
    "CirclePDF",
    "Column",
    "Component",
    "ComponentGroupCollision",
    "ComponentGroupOffCanvas",
    "ComponentGroup",
    "ComponentGroupPDF",
    "ComponentGroupSVG",
    "CubicBezierSVG",
    "CubicBezierDrawing",
    "CubicBezierPDF",
    "Document",
    "DocumentOutputFormat",
    "DocumentPDF",
    "DocumentSVG",
    "DrawingStyle",
    "DrawingComponentGroup",
    "DXFDocument",
    "DXFRenderContext",
    "ExtractionTruthAnnotation",
    "ExtractionTruthRecord",
    "FlattenedPath",
    "FlattenedSVG",
    "FlowDocument",
    "FitterShape",
    "FittingResult",
    "Font",
    "GrammarTruthAnnotation",
    "GrammarTruthRecord",
    "GradientStop",
    "IncludeLayer",
    "ImageDrawing",
    "ImagePDF",
    "ImageSVG",
    "IllegalArgumentError",
    "IncompatibleCanvas",
    "InvalidComponentGroupID",
    "InvalidComponentID",
    "InvalidConvexHull",
    "InvalidPolygonError",
    "Layer",
    "Layers",
    "LineSVG",
    "LineDrawing",
    "LinePDF",
    "LineSpacingRule",
    "LinearGradientFill",
    "OutputFormat",
    "PDFGeneratorInterface",
    "PDFRenderContext",
    "PositionedTextRun",
    "ParserStressBOMRow",
    "ParserStressFixtureSpec",
    "PathSVG",
    "PathDrawing",
    "PathPDF",
    "Paragraph",
    "ParagraphAlignment",
    "ParagraphLine",
    "PolygonalSVG",
    "PolygonalDrawing",
    "PolygonalPDF",
    "QuadraticBezierSVG",
    "QuadraticBezierDrawing",
    "QuadraticBezierPDF",
    "RasterImageAsset",
    "RasterImageComponent",
    "RasterBairdResult",
    "RasterRenderResult",
    "RectangleSVG",
    "RectangleDrawing",
    "RectanglePDF",
    "RegularPolygonSVG",
    "RegularPolygonDrawing",
    "RegularPolygonPDF",
    "Row",
    "StandardDrawingComponent",
    "Style",
    "SVGComponent",
    "SvgClipWindow",
    "ScannedParserStressFixtureSpec",
    "Table",
    "TableSVG",
    "TabStop",
    "TextBlock",
    "TextComponent",
    "TextFitter",
    "TextStyle",
    "TextSVG",
    "TextDrawing",
    "TextPDF",
    "Zoning",
    "ZoningDrawing",
    "annotate_extraction_truth",
    "annotate_grammar_truth",
    "build_parser_stress_pdf",
    "build_scanned_parser_stress_pdf",
    "baird_degrade",
    "baird_degrade_asset",
    "component_to_fitter_shape",
    "DEFAULT_PARSER_STRESS_BOM_ROWS",
    "extraction_truth_json",
    "emit_svg_region",
    "flatten_svg",
    "grammar_truth_json",
    "outline_for_text",
    "outline_for_text_bytes",
    "render_and_degrade_drawing_group",
    "render_drawing_group",
    "sigma_px_to_um",
    "sigma_um_to_px",
]
